# fly.toml app configuration file generated for lifeocr on 2026-01-08T05:17:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lifeocr'
primary_region = 'iad'
console_command = '/code/manage.py shell'

[build]

# プロセス定義（タイムアウト120秒、並列処理設定）
[processes]
  app = "gunicorn --bind :8000 --workers 1 --threads 8 --timeout 120 lifeocr.wsgi"

[env]
  PORT = '8000'
  # WEB_CONCURRENCYは上のコマンドで指定したのでコメントアウトのままでOK
  # WEB_CONCURRENCY = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  
  # ★★★ ここを追加（これがエラーの原因でした） ★★★
  # 上の [processes] で定義した 'app' をこのサービスで使うと宣言します
  processes = ['app']

  # 複数アクセス許可設定
  [http_service.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'