# fly.toml app configuration file generated for lifeocr on 2026-01-08T05:17:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lifeocr'
primary_region = 'iad'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'
  # 1つのマシンの中でいくつのプロセスを動かすか
  # メモリ2GBのマシンなら「1」か「2」が限界です。
  # 安全のため「1」推奨（OCRはメモリを食うため）
  WEB_CONCURRENCY = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']


[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
